asn: LocalASN
bgpq-args: "-S AFRINIC,APNIC,ARIN,LACNIC,RIPE"
default-route: false
irr-query-timeout: 30
irr-server: "rr.ntt.net"
merge-paths: true
peeringdb-api-key: "PeeringDB API key"
peeringdb-query-timeout: 30
prefixes:
  - "Prefixes that will be announce"
router-id: "Your router IPv4 (can be private IP)"
rtr-server: "rtr.rpki.cloudflare.com:8282"

kernel:
  learn: true

# BGP Large Communities
# LocalASN:1:1 - Learned from upstream
# LocalASN:1:2 - Learned from route server
# LocalASN:1:3 - Learned from peer
# LocalASN:1:4 - Learned from downstream

templates:
  upstream:
    add-on-import:
      - LocalASN:1:1
    allow-local-as: true
    announce:
      - LocalASN:1:4
    local-pref: 100
    remove-all-communities: LocalASN

  routeserver:
    add-on-import:
      - LocalASN:1:2
    announce:
      - LocalASN:1:4
    auto-import-limits: true
    enforce-first-as: false
    enforce-peer-nexthop: false
    filter-transit-asns: true
    local-pref: 200
    remove-all-communities: LocalASN

  peer:
    add-on-import:
      - LocalASN:1:3
    announce:
      - LocalASN:1:4
    auto-as-set: true
    auto-import-limits: true
    filter-irr: true
    filter-transit-asns: true
    irr-accept-child-prefixes: true
    local-pref: 300
    remove-all-communities: LocalASN

  downstream:
    add-on-import:
      - LocalASN:1:4
    allow-blackhole-community: true
    announce:
      - LocalASN:1:1
      - LocalASN:1:2
      - LocalASN:1:3
    auto-as-set: true
    auto-import-limits: true
    filter-irr: true
    filter-transit-asns: true
    irr-accept-child-prefixes: true
    local-pref: 400

  ibgp:
    allow-local-as: true
    asn: LocalASN
    direct: true
    enforce-first-as: false
    enforce-peer-nexthop: false
    filter-irr: false
    filter-rpki: false
    next-hop-self: true

peers:
############
# UPSTREAM #
############
  Upstream:
    asn: NeighborASN
    #disabled: true
    listen4: "LocalIP"
    listen6: "LocalIP"
    local-pref: 100
    neighbors:
      - "NeighborIP"
      - "NeighborIP"
    template: upstream

###############
# ROUTESERVER #
###############
  Routeserver:
    asn: NeighborASN
    #disabled: true
    listen4: "LocalIP"
    listen6: "LocalIP"
    local-pref: 200
    neighbors:
      - "NeighborIP"
      - "NeighborIP"
    template: routeserver

###########
# PEERING #
###########
  Peering:
    asn: NeighborASN
    #disabled: true
    listen4: "LocalIP"
    listen6: "LocalIP"
    local-pref: 300
    neighbors:
      - "NeighborIP"
      - "NeighborIP"
    template: peer

##############
# DOWNSTREAM #
##############
  Downstream:
    asn: NeighborASN
    #disabled: true
    listen4: "LocalIP"
    listen6: "LocalIP"
    local-pref: 400
    neighbors:
      - "NeighborIP"
      - "NeighborIP"
    template: downstream

############
# INTERNAL #
############
  iBGP_Upstream:
    add-on-import:
      - LocalASN:1:1
    announce:
      - LocalASN:1:1
    #disabled: true
    listen6: "fd2f:4e6:46c6::2"
    local-port: 179
    #local-pref: 150
    neighbor-port: 179
    neighbors:
      - "NeighborIP"
      - "NeighborIP"
    template: ibgp

  iBGP_Routeserver:
    add-on-import:
      - LocalASN:1:2
    announce:
      - LocalASN:1:2
    #disabled: true
    listen4: "LocalIP"
    listen6: "LocalIP"
    local-port: 189
    #local-pref: 250
    neighbor-port: 189
    neighbors:
      - "NeighborIP"
      - "NeighborIP"
    template: ibgp

  iBGP_Peering:
    add-on-import:
      - LocalASN:1:3
    announce:
      - LocalASN:1:3
    #disabled: true
    listen4: "LocalIP"
    listen6: "LocalIP"
    local-port: 199
    #local-pref: 350
    neighbor-port: 199
    neighbors:
      - "NeighborIP"
      - "NeighborIP"
    template: ibgp

  iBGP_Downstream:
    add-on-import:
      - LocalASN:1:4
    announce:
      - LocalASN:1:4
    #disabled: true
    listen4: "LocalIP"
    listen6: "LocalIP"
    local-port: 209
    local-pref: 400
    neighbor-port: 209
    neighbors:
      - "NeighborIP"
      - "NeighborIP"
    template: ibgp
